version: '2.0'

www:
  image: nginx:alpine
  volumes:
    - ./etc/nginx/conf.d/default.conf.nginx:/etc/nginx/conf.d/default.conf
  ports: 
    - 80:80
  depends_on:
    - backend
    - frontend

backend:
  build: 
    context: dockerize/backend
  user: ${UID}:${UID}
  volumes:
    - ./backend:/app
    - ./etc/php:/usr/local/etc/php/local.conf.d
  environment:
    PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
  command: "php artisan serve --host=0.0.0.0 --port=8080"

frontend:
  image: node:current-alpine
  user: ${UID}:${uid}
  working_dir: /home/node/app
  voulmes:
    - ./frontend:/home/node/app
  environment:
    NODE_ENV: development
  command: "npm run serve"